version: "3.8"

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=database
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: backend
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host 

volumes: 
  pgdata: 
    driver: local
